branch-defaults:
  default:
    environment: strive-webapp-dev
    group_suffix: null
global:
  application_name: strive-webapp
  branch: null
  default_ec2_keyname: strive-webapp-dev
  default_platform: python2.7
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli-strive
  repository: null
  sc: null
  workspace_type: Application
